language: python
python:
  - "2.7"
services:
  - redis-server
addons:
  postgresql: "9.3"
env:
  global:
    - PGUSER=postgres
script:
  - ./test.sh
before_install:
  sudo apt-get update -qq
  sudo apt-get install -y fabric
