language: python
sudo: false
python:
  - "2.7"
  - "3.4"
services:
  - redis-server
addons:
  postgresql: "9.3"
  apt:
    packages:
    - fabric
    - nodejs
    - npm
env:
  global:
    - PGUSER=postgres
script:
  - ./test.sh
before_install:
  - npm install -g bower jshint
