linters:
  DuplicateProperty:
    # Allow fallback properties (dumb browsers first, better rules for smart
    # browsers next)
    enabled: false
  StringQuotes:
    # We really do not care that much about quote characters.
    enabled: false
  HexNotation:
    # Do not complain about lowercase/uppercase.
    enabled: false
  HexLength:
    # No shorthand notation for colors.
    style: long
  ZeroUnit:
    # Sometimes, units make a rule easier to understand. It might even be
    # necessary sometimes for SCSS.
    enabled: false
